steps:
  - task: DotNetCoreCLI@2
    displayName: Restore packages [dotnet restore]
    inputs:
      command: restore
      projects: $(projectSolution)
      verbosityRestore: normal
      testRunTitle: $(Agent.JobName)

  - task: DotNetCoreCLI@2
    displayName: Build source [dotnet build $(buildConfiguration)]
    inputs:
      command: build
      projects: $(projectSolution)
      arguments: --configuration $(BuildConfiguration) --no-restore  -p:Version=$(Build.BuildNumber) -p:langversion=latest
      testRunTitle: $(Agent.JobName)
